- Generally ML models Developed by maths
- Convert categorical column to Numerical columns
- Here we are transform the data
- This method is called as Encoding
- Feature Analaysis: first 5 sessions
- Feature Enginerring: Transform the data
- Feature selection: Machine learning

- Before Model Development
- we will do EDA : Exploratry data analysis 
  - Features (columns) analysis
   - categorical ,Numerical ,outlier analysis, Biveriate ,Multivariate
   - we will get the insights
- Feature Engineering
  - we will modify the data
  - Encoding : convert categorical data to Numerical Variables
  - scaling : All the numerical columns makes under one scale
  - Transformations : All the maths developed by assumption data follows Normal distribution
  - convert skewed distribution to Normal
- Feature selection

- map
- LabelEncoder
- OneHotEncoder

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
path='Visadataset.csv'
visa_df=pd.read_csv(path)
visa_df
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [2]:
# check how many unique values avaliable
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [3]:
# create a dictionary assigin a number start with  Zero
# foe each labels based on alpabetical order
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [4]:
# map the dictionary with column
visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [5]:
visa_df['case_status']=visa_df['case_status'].map(d)

In [6]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [7]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)
visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)

In [8]:
lables=sorted(visa_df['continent'].unique())
d={}
for i in range (len(lables)):
    key=lables[i]
    d[key]=i

In [9]:
lables=sorted(visa_df['continent'].unique())
d={lables[i]:i for i in range (len(lables))}
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [10]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)
labels=sorted(visa_df['continent'].unique())
d={lables[i]:i for i in range (len(lables))}
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [11]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
for i in cat:
    lables=sorted(visa_df[i].unique())
    d={lables[i]:i for i in range (len(lables))}
    visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**LabelEncoder**

- package name:**sklearn**
  - class: **preprocessing**
    - method: **LabelEncoder**
- from sklearn: preprocessing import LabelEncoder

- step-1: import the method
- step-2: save the method
- step-3: apply fit transform
**fit transform**
- fit: finding something
     - first  we are finding dictionary
- transform: change the data
- using the dictionary we are changing Eng to Number

In [12]:
from sklearn.preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0])

In [13]:
from sklearn. preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)
le=LabelEncoder()
for i in cat:
    visa_df[i]=le.fit_transform(visa_df[i])

In [14]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**OneHotEncoder**

- the method name is: pd.get_dummies
 |case_status|case_status_Denied|case_status_Certified|
|-|-|-|
|Denied|1|0|
|Certified|1|0|

In [15]:
path='Visadataset.csv'
visa_df=pd.read_csv(path)
pd.get_dummies(visa_df['continent'],
              dtype='int')

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [16]:
visa_df['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

**LableEncoder vs OneHotEncoder**

In [ ]:
- Generally we dont want a relaton between input columns
- we need both input columns are not corrrelated each other
- we need both input columns are **independent(X,Y)**each other
- we need both input columns are **prependicular** each other
- we need both input columns are **Orthogonal** each other
- we need both input columns are **90 degrees phase shift** each other
- OneHotEncoder will achieve above
- But