In [2]:
==================== Data Analysis =============================
1. Pandas         :  Data frame analysis
2. Numpy          :  Numerical analysis
3. matplotlib     :  Graphs and plots
4. seaborn        :  plots
5. Bokhe         :   plots
6. plotly         :  plots

=================== Machine Learning ============================
7. stats          : for statistical models
8. scikit-learn(sklearn) :  ML models

===================  Deep learning ============================
9. opencv         : Computer vision
10. pillow        : Image operations
11. tensorflow    : Neural Network creations (developed by google)
12. keras         : NN
13. pytorch       : alternative package of tensorflow (facebook meta)

==================== NLP ========================================
14. NLTK          : Natural language toolkit
15. SpaCy         : Alternative to NLTK
16. wordcloud     : most frequent occured words       

======================= Scarapping =================================
17. SqLite        : Data base creation
18. Beautiful soup
19. Selenium

======================== API creations ===========================
20. Flask
21. FastAPI
22. Gradio
23. Django
======================= UI app creation =========================
24.Streamlit

===================== Transfer learning models(DL) ===========
25. Mobilenet
26. Resnet
27. VGGnet
28. Inception
29. Yolo    :  Ultralytics

===================== Transfer learning models(NLP) ===========
30. Word2vec
31. GloVe

======================== Huging Face Transformers ===============
32. BERT   : Bi Directional Encoder representation of Transformers

========================== Allen NLP =======================
33. Allen NLP packages

================== GenAI =============================
34. LangChain
35. Google GeminiAi realted pcakges
36. OpenAI GPT realted packages
37. Amazon BedRock realted packages
38. Meta Llama  related packages

==================== Image and Video Generations ==============
39. GAN models realted packages
40. SORA related packages

=================== Model deployment (MlOps)===================
41. mlflow using databricks
42. kubeflow (GCP account)

==================== Cloud applications =====================
43. Azure ML realted packages
44. GCP VertexAI related packages
45. AWS Sagemaker realted packages

==================== small ===================================
46. time
47. logging
48. math
49. random
50. env
51. os

SyntaxError: invalid decimal literal (3996392081.py, line 36)

**Step-1: Import packages**

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: create a Dataframe using list**

- data : your data either list or dict

- index : we need to provide a list

- columns : we need to provide a list

In [9]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
             columns=['Names'])
# pd.DataFrame(data,index,columns)

    Names
0  Ramesh
1  Suresh
2  Satish

**Step-3: change the index**

In [10]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
             index=['A','B','C'],
             columns=['Names'])

    Names
A  Ramesh
B  Suresh
C  Satish

In [11]:
names=['Ramesh','Suresh','Satish']
idx=['A','B','C']
cols=['Names']
pd.DataFrame(names,
             index=idx,
             columns=cols)

    Names
A  Ramesh
B  Suresh
C  Satish

**Step-4: Add multiple columns**

In [12]:
names=['Ramesh','Suresh','Satish']
age=[20,22,24]
pd.DataFrame(zip(names,age),
            columns=['Names','Age'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

**Step-5: Create empty dataframe and update the columns**

In [13]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

**Step-6: Add a new column with existing dataframe**

In [14]:
names=['Ramesh','Suresh','Satish']
age=[20,22,24]
df=pd.DataFrame(zip(names,age),
            columns=['Names','Age'])
df['City']=['Hyd','Pune','Blr']
df

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Satish   24   Blr

**Step-7: overwrite the column values**

- I want to overwrite my age values

- originally age is = [20,22,24]

- now i want to update the age = [30,32,34]

In [15]:
df['Age']=[30,32,34]
df['age']=[30,32,34]
df

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

**Step-8:Drop the column**

- labels

- axis

- index

- columns

- inplace

In [16]:
df

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [17]:
df.drop('age')   # error
df.drop('age',axis=0) # error
df.drop('age',axis=1) # correct
# here python assume age is a label
# python ask qn : is it index label or column label
# axis=1 means for columns
# axis=0 means for rows
# by default axis=0

KeyError: "['age'] not found in axis"

In [ ]:
df.drop('age',axis=1) 
df

In [ ]:
df # we are able to see old column
# becuase we did not apply inplace=True

In [ ]:
# whenever we use columns label 
# no need of axis
df.drop(columns=['age'],
        inplace=True)

In [ ]:
df

In [18]:
# drop index= 2
df.drop(2,
        axis=0)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32

In [19]:
df.drop(index=2)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32

**step-9:rename the column**

- mapper: dictionary{'city:city}
- index:
- columns:{'city'}
- axis:
- inplace:

In [20]:
df
# i want to change city column: city

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [21]:
dict1={'city':'city'}
df.rename(dict1)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [22]:
dict1={'city':'city'}
df.rename(dict1,axis=1)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [23]:
dict1={'city':'city'}
df.rename(columns=dict1)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [24]:
df

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [25]:
dict1={'city':'city'}
df.rename(columns=dict1,
          inplace=True)
df

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [26]:
# can you change 2 to 'B'
# sir whats the difference between labels and index and index sir?
#index 0,1,2
# column Names ,Age ,city
# label:Names 0

In [27]:
dict1={2:'B'}
df.rename(dict1,axis=0)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
B  Satish   34   Blr   34

In [28]:
dict1={2:'B'}
df.rename(index=dict1)

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
B  Satish   34   Blr   34

In [29]:
df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i**2 for i in range(1,10)]
df1['cube_value']=[i**3 for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

- lens
- column
- shape
- dtypes
- head
- tail

In [30]:
df1.columns

Index(['value', 'square_value', 'cube_value'], dtype='object')

In [31]:
list(df1.columns)

['value', 'square_value', 'cube_value']

In [32]:
df1.columns.to_list()

['value', 'square_value', 'cube_value']

In [33]:
df1.shape
# 9 rows and 3 columns

(9, 3)

In [34]:
df1.dtypes
# integer we will get integer
# float we will get float
# string we will get object

value           int64
square_value    int64
cube_value      int64
dtype: object

In [35]:
df.dtypes

Names    object
Age       int64
City     object
age       int64
dtype: object

In [36]:
df1.head(2)

   value  square_value  cube_value
0      1             1           1
1      2             4           8

In [37]:
df1.tail()

   value  square_value  cube_value
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [38]:
len(df1)

9

In [39]:
df1.isnull()
# we are asking a qn
# a null value availbel or not
# True or False
# True means yes NULL available
# False means No NULL value not available

   value  square_value  cube_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False

In [40]:
df1.isnull().sum()
# column wise null value count will display

value           0
square_value    0
cube_value      0
dtype: int64

In [41]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         9 non-null      int64
 1   square_value  9 non-null      int64
 2   cube_value    9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

Step-10
- How to change a specific value of a column
- df1.drop
- either it will drop column or index
- df1.rename
- either it will rename column or index
- df1.replace

In [42]:
df1
# replace cube_vlaue 64 to 464

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [43]:
df1.replace(64,464)# all the data will replace
df1.replace({64:464,1:111})# all the data will replace

   value  square_value  cube_value
0    111           111         111
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

**Step-11: Selection of a column**

In [44]:

df1['cube_value']
# series
# series looks like dataframe
# rows and columns

0      1
1      8
2     27
3     64
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [45]:
type(df1)

pandas.core.frame.DataFrame

In [46]:
type(df1['cube_value'])

pandas.core.series.Series

In [47]:
df1.shape # 2D

(9, 3)

In [48]:
df1['cube_value'].shape
# 1D data

(9,)

In [49]:
df1[['cube_value']]

   cube_value
0           1
1           8
2          27
3          64
4         125
5         216
6         343
7         512
8         729

In [50]:
type(df1[['cube_value']])
df1[['cube_value']].shape

(9, 1)

In [51]:
# square_value
# cube_value
# multiple always keep those in list
df1[['cube_value','square_value']]

   cube_value  square_value
0           1             1
1           8             4
2          27             9
3          64            16
4         125            25
5         216            36
6         343            49
7         512            64
8         729            81

In [52]:
df1['cube_value'].replace(64,464,inplace=True)

In [53]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

**step-12 : How to append a row**

- loc
- iloc

In [54]:
# df1.loc[rows,columns]
# df1.iloc[rows,columns]
# we can select particular rows and columns using a list: [start:stop:step]
df1.iloc[3:7,1:3]
df1.loc[3:7,['square_value','cube_value']]
cols=['square_value','cube_value']
df1.loc[3:7,cols]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343
7            64         512

In [ ]:
df1.iloc[[2,3,4]] #
df1.iloc[[2]]
df1.iloc[2]
df1.iloc[[2,3,4],[0,2]]
df1.iloc[2,0]
df1.iloc[:,0]
df1.iloc[2,:]
df1.iloc[[2],:]
df1.iloc[2:6,0]
df1.iloc[2:6,[0]]

In [56]:
df1.iloc[[2,3,4]]
# selecting 3 rows, all the columns
# dataframe

   value  square_value  cube_value
2      3             9          27
3      4            16         464
4      5            25         125

In [57]:
df1.iloc[[2]] # 2D df

   value  square_value  cube_value
2      3             9          27

In [58]:
df1.iloc[2] # 1D series

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [59]:
df1.iloc[[2,3,4],[0,2]]
# 2,3,4 row
# 0 and 2nd index (1,3)

   value  cube_value
2      3          27
3      4         464
4      5         125

In [60]:
df1.iloc[2,0]

np.int64(3)

In [61]:
df1
# in column1 (value) i want to replace value to 60
# based on specific index
df1.iloc[5,0]

np.int64(6)

In [62]:
df1.iloc[:,0]
# rows and first column

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: value, dtype: int64

In [63]:
df1.iloc[2,:]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [64]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [65]:
df1.iloc[[2],:]

   value  square_value  cube_value
2      3             9          27

In [66]:
df1.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: value, dtype: int64

In [67]:
df1.iloc[2:6,[0]]

   value
2      3
3      4
4      5
5      6

**How to append a row**

In [68]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [ ]:
df1.loc[9]=[10,100,1000]

In [69]:
len(df1)

9

In [70]:
ID=len(df1)
df1.loc[ID]=[10,100,1000]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

**Step-13: Save the dataframe**
- we can save dataframes in two ways
- .csv
- .xlsx
- where I want to save : directory
- what the the filename to save: filename
- what is the type of a file : extension
- different folder : r"C:\Users\honey\Documents\EDA Sessions\data1.csv"
- different folder : r"C:\Users\honey\Documents\EDA Sessions\data1.xlsx"
- same folder: r"data1.csv" or r"data1.xlsx"

In [71]:
csv_path=r"C:\Users\honey\Documents\EDA Sessions\data1.csv"
excel_path=r"C:\Users\honey\Documents\EDA Sessions\data1.xlsx"
df1.to_csv(csv_path) # index column created extra
df1.to_excel(excel_path) # index column created extra

In [72]:
csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path) # index column created extra
df1.to_excel(excel_path) # index column created extra

**Step-14 read the data**

In [73]:
csv_path=r"data1.csv"
pd.read_csv(csv_path)

   Unnamed: 0  value  square_value  cube_value
0           0      1             1           1
1           1      2             4           8
2           2      3             9          27
3           3      4            16         464
4           4      5            25         125
5           5      6            36         216
6           6      7            49         343
7           7      8            64         512
8           8      9            81         729
9           9     10           100        1000

In [74]:
excel_path=r"data1.xlsx"
pd.read_excel(excel_path)

   Unnamed: 0  value  square_value  cube_value
0           0      1             1           1
1           1      2             4           8
2           2      3             9          27
3           3      4            16         464
4           4      5            25         125
5           5      6            36         216
6           6      7            49         343
7           7      8            64         512
8           8      9            81         729
9           9     10           100        1000

In [75]:
csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path,index=False) # index column created extra
df1.to_excel(excel_path,index=False) # index column created extra

In [76]:
csv_path=r"data1.csv"
pd.read_csv(csv_path)

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000